// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
using System;
using System.Diagnostics;
using TicTacCOSTCO.AIs.Search;
using TicTacCOSTCO.DataStructures;
using UnityEngine;

[CreateAssetMenu(fileName = "AICore_Search.asset", menuName = "COSTCO/Budgeted Search AI Core")]
public sealed class AISearchCore : AICore
{
    public CpuStrength Strength = CpuStrength.Normal;
    [Range(0.1f, 4f)] public float WorkBudgetScale = 1;
    [Min(1)] public int MaxTreeNodes = 1024;
    [Min(1)] public int MoveTimeLimitMilliseconds = 500;
    [Range(0.1f, 8f)] public float FrameBudgetMilliseconds = 2;
    [Range(-2f, 2f)] public float ActivationPreference = 0;
    [Range(0f, 2f)] public float InvestmentWeight = 1;
    public int Seed = 12345;

    public CascadeSearch BeginSearch(int forSide, GameState game)
    {
        if (game == null) throw new ArgumentNullException(nameof(game));
        if (forSide != game.CurrentPlayerIndex) throw new ArgumentException("CPU may only choose for the current player.");
        var position = CascadePosition.Capture(game);
        var settings = SearchSettings.ForPosition(Strength, position.EmptyCount, position.ActiveCount);
        float scale = float.IsNaN(WorkBudgetScale) ? 1 : Mathf.Clamp(WorkBudgetScale, 0.1f, 4f);
        settings.MaxWorkUnits = (int)(settings.MaxWorkUnits * scale);
        settings.MaxNodes = Math.Max(1, Math.Min(16384, MaxTreeNodes));
        settings.ActivationPreference = ActivationPreference;
        settings.InvestmentWeight = InvestmentWeight;
        settings.Seed = unchecked(Seed ^ (int)position.Fingerprint());
        return new CascadeSearch(position, settings);
    }

    // Compatibility entry point. AIThinkerLoop uses BeginSearch instead, slicing work
    // across frames. Callers of this synchronous API are responsible for their thread.
    public override Coordinate DetermineMove(int forSide, GameState currentGameState)
    {
        using (var search = BeginSearch(forSide, currentGameState))
        {
            var clock = Stopwatch.StartNew();
            while (!search.IsComplete && clock.Elapsed.TotalMilliseconds < Math.Max(1, MoveTimeLimitMilliseconds))
                search.Step(1);
            if (!search.IsComplete) search.Stop(SearchStopReason.Deadline);
            if (!search.BestMove.HasValue) throw new InvalidOperationException("No legal CPU move.");
            return search.BestMove.Value;
        }
    }
}
