// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
namespace TicTacCOSTCO.AIs.Search
{
    using System;
    using System.Collections.Generic;
    using System.Threading;
    using TicTacCOSTCO.DataStructures;

    /// <summary>
    /// Resumable reward-vector MCTS. Each yield bounds work to one candidate/position
    /// operation, allowing the host to enforce frame and wall-clock budgets.
    /// No permanent spatial pruning: progressive widening can admit every ranked move.
    /// </summary>
    public sealed class CascadeSearch : IDisposable
    {
        private struct Candidate
        {
            public int Move;
            public double Score;
            public bool Survives;
        }
        private sealed class Node
        {
            public int Move;
            public int Visits;
            public Candidate[] Candidates;
            public readonly double[] Rewards;
            public readonly List<Node> Children = new List<Node>();
            public Node(int move, int players) { Move = move; Rewards = new double[players]; }
        }
        private sealed class ExactValue { public double Value; }

        private readonly CascadePosition original;
        private readonly CascadePosition scratch;
        private readonly SearchSettings settings;
        private readonly Random random;
        private readonly Node root;
        private readonly IEnumerator<int> routine;
        private readonly int[] emptyMoves;
        private readonly double[] reward;
        private readonly List<Node> path = new List<Node>();
        private int bestMove = -1;
        private double fallbackScore = double.NegativeInfinity;
        private int nodeCount = 1;
        private bool finalized;

        public int WorkUnits { get; private set; }
        public int Simulations { get; private set; }
        public int NodeCount => nodeCount;
        public bool RootScanComplete { get; private set; }
        public bool IsProven { get; private set; }
        public SearchStopReason StopReason { get; private set; } = SearchStopReason.Running;
        public bool IsComplete => StopReason != SearchStopReason.Running;
        public Coordinate? BestMove => bestMove < 0 ? (Coordinate?)null : original.CoordinateOf(bestMove);

        public CascadeSearch(CascadePosition position, SearchSettings configuration)
        {
            if (position == null) throw new ArgumentNullException(nameof(position));
            settings = (configuration ?? throw new ArgumentNullException(nameof(configuration))).ValidatedCopy();
            original = position.Clone();
            scratch = position.Clone();
            random = new Random(settings.Seed);
            root = new Node(-1, position.PlayerCount);
            emptyMoves = new int[position.CellCount];
            reward = new double[position.PlayerCount];
            if (!position.IsTerminal && position.IsActive(position.CurrentPlayer))
                for (int i = 0; i < position.CellCount; i++)
                    if (position.IsLegal(i)) { bestMove = i; break; }
            if (bestMove < 0) StopReason = SearchStopReason.NoLegalMove;
            routine = Run().GetEnumerator();
        }

        public void Step(int workUnits, CancellationToken cancellation = default)
        {
            if (workUnits < 0) throw new ArgumentOutOfRangeException(nameof(workUnits));
            for (int i = 0; i < workUnits && !IsComplete; i++)
            {
                if (cancellation.IsCancellationRequested) { Stop(SearchStopReason.Cancelled); break; }
                if (WorkUnits >= settings.MaxWorkUnits) { Stop(SearchStopReason.WorkLimit); break; }
                if (!routine.MoveNext()) { Stop(IsProven ? SearchStopReason.Solved : SearchStopReason.SimulationLimit); break; }
                WorkUnits++;
            }
            if (!IsComplete && WorkUnits >= settings.MaxWorkUnits) Stop(SearchStopReason.WorkLimit);
        }

        public void Stop(SearchStopReason reason = SearchStopReason.Cancelled)
        {
            if (IsComplete) return;
            if (reason == SearchStopReason.Running) throw new ArgumentException("A stop requires a reason.");
            StopReason = reason;
            FinalizeMove();
            routine.Dispose();
        }

        public void Dispose() { Stop(); routine.Dispose(); }

        private IEnumerable<int> Rank(Node node, CascadePosition position, bool isRoot)
        {
            var candidates = new List<Candidate>(position.EmptyCount);
            bool anySafe = false;
            int player = position.CurrentPlayer;
            for (int i = 0; i < position.CellCount; i++)
            {
                if (!position.IsLegal(i)) continue;
                int connections = position.CountConnections(i, player);
                bool safe = position.Phase != GameState.GameStateEnum.Cascade || connections >= position.Threshold;
                double score = MoveScore(position, i, player, connections) + random.NextDouble() * 0.001;
                candidates.Add(new Candidate { Move = i, Score = score, Survives = safe });
                anySafe |= safe;
                if (isRoot && score > fallbackScore) { fallbackScore = score; bestMove = i; }
                yield return 0;
            }
            // Under winner/surviving-draw utility, voluntary immediate elimination cannot
            // improve one's result. Do not remove moves when every move eliminates us.
            if (anySafe) candidates.RemoveAll(c => !c.Survives);
            candidates.Sort((a, b) => b.Score.CompareTo(a.Score));
            node.Candidates = candidates.ToArray();
            if (isRoot)
            {
                RootScanComplete = true;
                if (node.Candidates.Length > 0) bestMove = node.Candidates[0].Move;
            }
            yield return 0;
        }

        private double MoveScore(CascadePosition position, int move, int player, int connections)
        {
            if (position.Phase == GameState.GameStateEnum.Cascade && connections < position.Threshold)
                return -1000000;
            double investment = position.Investment(move, player);
            double denial = 0;
            for (int p = 0; p < position.PlayerCount; p++)
                if (p != player && position.IsActive(p))
                    denial = Math.Max(denial, position.CountConnections(move, p) * 3 +
                        position.Investment(move, p) * 0.25);
            return connections * (3 + settings.ActivationPreference) +
                settings.InvestmentWeight * Math.Log(1 + investment) + denial;
        }

        private IEnumerable<int> Run()
        {
            if (IsComplete) yield break;
            foreach (int unit in Rank(root, original, true)) yield return unit;
            if (original.ActiveCount == 2 && original.EmptyCount <= settings.ExactEmptyLimit)
            {
                double best = double.NegativeInfinity;
                int solvedMove = bestMove;
                foreach (var candidate in root.Candidates)
                {
                    var next = original.Clone();
                    next.Apply(candidate.Move);
                    var result = new ExactValue();
                    foreach (int unit in Solve(next, original.CurrentPlayer, best, double.PositiveInfinity, result))
                        yield return unit;
                    if (result.Value > best) { best = result.Value; solvedMove = candidate.Move; }
                    if (best == 1) break; // A proven win cannot be improved.
                }
                bestMove = solvedMove;
                IsProven = true;
                yield break;
            }
            while (Simulations < settings.MaxSimulations)
            {
                scratch.CopyFrom(original);
                path.Clear();
                path.Add(root);
                Node node = root;
                while (!scratch.IsTerminal)
                {
                    if (node.Candidates == null)
                        foreach (int unit in Rank(node, scratch, false)) yield return unit;
                    if (node.Candidates.Length == 0) break;
                    int allowed = Math.Min(node.Candidates.Length, Math.Max(settings.InitialCandidates,
                        (int)Math.Ceiling(settings.Widening * Math.Sqrt(node.Visits + 1))));
                    if (node.Children.Count < allowed && nodeCount < settings.MaxNodes)
                    {
                        int move = node.Candidates[node.Children.Count].Move;
                        var child = new Node(move, original.PlayerCount);
                        node.Children.Add(child);
                        nodeCount++;
                        scratch.Apply(move);
                        node = child;
                        path.Add(node);
                        yield return 0;
                        break;
                    }
                    if (node.Children.Count == 0) break; // Node cap: evaluate by rollout instead.
                    node = Select(node, scratch.CurrentPlayer);
                    scratch.Apply(node.Move);
                    path.Add(node);
                    yield return 0;
                }
                for (int ply = 0; ply < settings.RolloutPlies && !scratch.IsTerminal; ply++)
                {
                    int count = scratch.FillEmptyMoves(emptyMoves);
                    if (count == 0) break;
                    int samples = scratch.Phase == GameState.GameStateEnum.Cascade
                        ? count : Math.Min(count, settings.RolloutCandidates);
                    int chosen = emptyMoves[0];
                    double best = double.NegativeInfinity;
                    for (int j = 0; j < samples; j++)
                    {
                        int k = random.Next(j, count);
                        int move = emptyMoves[k];
                        emptyMoves[k] = emptyMoves[j];
                        emptyMoves[j] = move;
                        int connections = scratch.CountConnections(move, scratch.CurrentPlayer);
                        double value = MoveScore(scratch, move, scratch.CurrentPlayer, connections) + random.NextDouble();
                        if (value > best) { best = value; chosen = move; }
                        yield return 0;
                    }
                    scratch.Apply(chosen);
                    yield return 0;
                }
                foreach (int unit in Evaluate(scratch)) yield return unit;
                foreach (Node visited in path)
                {
                    visited.Visits++;
                    for (int p = 0; p < reward.Length; p++) visited.Rewards[p] += reward[p];
                }
                Simulations++;
                UpdateBestMove();
                yield return 0;
            }
        }

        // Full-width alpha-beta only in small two-survivor positions. Interrupted
        // recursion never promotes a partial bound to a proof or overwrites fallback.
        private IEnumerable<int> Solve(CascadePosition position, int rootPlayer,
            double alpha, double beta, ExactValue result)
        {
            yield return 0;
            if (position.IsTerminal)
            {
                result.Value = position.Winner.HasValue ? (position.Winner.Value == rootPlayer ? 1 : 0) : .5;
                yield break;
            }
            bool maximize = position.CurrentPlayer == rootPlayer;
            double value = maximize ? double.NegativeInfinity : double.PositiveInfinity;
            for (int i = 0; i < position.CellCount; i++)
            {
                if (!position.IsLegal(i)) continue;
                var next = position.Clone();
                next.Apply(i);
                var child = new ExactValue();
                foreach (int unit in Solve(next, rootPlayer, alpha, beta, child)) yield return unit;
                value = maximize ? Math.Max(value, child.Value) : Math.Min(value, child.Value);
                if (maximize) alpha = Math.Max(alpha, value); else beta = Math.Min(beta, value);
                if (alpha >= beta) break;
            }
            result.Value = value;
        }

        private Node Select(Node parent, int player)
        {
            Node best = parent.Children[0];
            double bestValue = double.NegativeInfinity;
            foreach (Node child in parent.Children)
            {
                double value = child.Visits == 0 ? double.PositiveInfinity :
                    child.Rewards[player] / child.Visits +
                    settings.Exploration * Math.Sqrt(Math.Log(parent.Visits + 1) / child.Visits);
                if (value > bestValue) { bestValue = value; best = child; }
            }
            return best;
        }

        private IEnumerable<int> Evaluate(CascadePosition position)
        {
            Array.Clear(reward, 0, reward.Length);
            if (position.IsTerminal)
            {
                if (position.Winner.HasValue) reward[position.Winner.Value] = 1;
                else
                    for (int p = 0; p < reward.Length; p++)
                        if (position.IsActive(p)) reward[p] = 1.0 / Math.Max(1, position.ActiveCount);
                yield return 0;
                yield break;
            }
            // Cutoff heuristic is deliberately bounded and distinct from terminal proof.
            double total = 0;
            for (int p = 0; p < reward.Length; p++)
            {
                if (!position.IsActive(p)) continue;
                int responses = 0, scoring = 0;
                double investment = 0;
                for (int i = 0; i < position.CellCount; i++)
                {
                    if (!position.IsLegal(i)) continue;
                    int count = position.CountConnections(i, p);
                    if (count >= Math.Max(1, position.Threshold)) responses++;
                    if (count > 0) scoring++;
                    investment += position.Investment(i, p);
                    yield return 0;
                }
                double value = 1 + Math.Log(1 + responses) * 2 + Math.Log(1 + scoring) +
                    0.1 * settings.InvestmentWeight * Math.Log(1 + investment / Math.Max(1, position.EmptyCount));
                if (position.Phase == GameState.GameStateEnum.Cascade && responses == 0) value *= 0.05;
                reward[p] = value;
                total += value;
            }
            if (total > 0)
                for (int p = 0; p < reward.Length; p++) reward[p] /= total;
            yield return 0;
        }

        private void UpdateBestMove()
        {
            Node best = null;
            foreach (Node child in root.Children)
                if (child.Visits > 0 && (best == null || child.Visits > best.Visits ||
                    (child.Visits == best.Visits && child.Rewards[original.CurrentPlayer] / child.Visits >
                     best.Rewards[original.CurrentPlayer] / best.Visits))) best = child;
            if (best != null) bestMove = best.Move;
        }

        private void FinalizeMove()
        {
            if (finalized) return;
            finalized = true;
            if (IsProven) return;
            UpdateBestMove();
            if (settings.RootChoiceNoise <= 0 || random.NextDouble() >= settings.RootChoiceNoise) return;
            // Sample only reasonably close evaluated choices, never reintroducing an
            // immediately losing move removed by the root safety pass.
            double bestValue = double.NegativeInfinity;
            foreach (Node child in root.Children)
                if (child.Visits > 0) bestValue = Math.Max(bestValue, child.Rewards[original.CurrentPlayer] / child.Visits);
            int eligible = 0;
            foreach (Node child in root.Children)
                if (child.Visits > 0 && child.Rewards[original.CurrentPlayer] / child.Visits >= bestValue - 0.15)
                    if (random.Next(++eligible) == 0) bestMove = child.Move;
        }
    }
}
