// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
namespace TicTacCOSTCO.AIs.Search
{
    using System;
    using TicTacCOSTCO.DataStructures;

    /// <summary>
    /// Detached search state. A consumed-direction bit per cell is equivalent to
    /// GameState.PruneSolutionsForNotAlreadySolved for legal, placement-only play.
    /// No Unity objects, callbacks, global random state, or game mutations.
    /// </summary>
    public sealed class CascadePosition
    {
        private static readonly int[] Dx = { 1, 1, 0, -1 };
        private static readonly int[] Dy = { 0, -1, -1, -1 };
        private readonly int[] owners;
        private readonly byte[] consumed;
        private readonly bool[] active;

        public int Width { get; }
        public int Height { get; }
        public int PlayerCount { get; }
        public int ConnectionLength { get; }
        public int CellCount => owners.Length;
        public int EmptyCount { get; private set; }
        public int CurrentPlayer { get; private set; }
        public int ActiveCount { get; private set; }
        public int Threshold { get; private set; }
        public GameState.GameStateEnum Phase { get; private set; }
        public int? Winner { get; private set; }
        public bool IsTerminal => Phase == GameState.GameStateEnum.End;

        private CascadePosition(int width, int height, int players, int length)
        {
            Width = width;
            Height = height;
            PlayerCount = players;
            ConnectionLength = length;
            owners = new int[checked(width * height)];
            consumed = new byte[owners.Length];
            active = new bool[players];
        }

        public static CascadePosition Capture(GameState game)
        {
            if (game == null) throw new ArgumentNullException(nameof(game));
            if (game.Width < 1 || game.Height < 1 || game.PlayerCount < 1 ||
                game.InARowToSolve < 2 || game.CurrentPlayerIndex < 0 ||
                game.CurrentPlayerIndex >= game.PlayerCount)
                throw new ArgumentException("Invalid game dimensions, players, or connection length.");
            var result = new CascadePosition(game.Width, game.Height, game.PlayerCount, game.InARowToSolve);
            for (int i = 0; i < result.CellCount; i++)
            {
                var cell = result.CoordinateOf(i);
                if (!game.SpotToSideOwnership.TryGetValue(cell, out int? owner))
                    throw new ArgumentException("Snapshot must contain every board cell.");
                if (owner.HasValue && (owner.Value < 0 || owner.Value >= game.PlayerCount))
                    throw new ArgumentException("Invalid cell owner.");
                result.owners[i] = owner ?? -1;
                if (!owner.HasValue) result.EmptyCount++;
                if (!game.AcceptedSolutions.TryGetValue(cell, out var solutions)) continue;
                foreach (var solution in solutions)
                    for (int d = 0; d < 4; d++)
                        if (solution.Directionality.X == Dx[d] && solution.Directionality.Y == Dy[d])
                            result.consumed[i] |= (byte)(1 << d);
            }
            foreach (int player in game.SideIndexesStillInGame)
            {
                if (player < 0 || player >= game.PlayerCount) throw new ArgumentException("Invalid active player.");
                result.active[player] = true;
                result.ActiveCount++;
            }
            result.CurrentPlayer = game.CurrentPlayerIndex;
            result.Threshold = game.LastCascade;
            result.Phase = game.CurrentGameState;
            result.Winner = game.Winner;
            return result;
        }

        public CascadePosition Clone()
        {
            var copy = new CascadePosition(Width, Height, PlayerCount, ConnectionLength);
            copy.CopyFrom(this);
            return copy;
        }

        internal void CopyFrom(CascadePosition other)
        {
            if (Width != other.Width || Height != other.Height || PlayerCount != other.PlayerCount ||
                ConnectionLength != other.ConnectionLength) throw new ArgumentException("Incompatible position.");
            Array.Copy(other.owners, owners, owners.Length);
            Array.Copy(other.consumed, consumed, consumed.Length);
            Array.Copy(other.active, active, active.Length);
            EmptyCount = other.EmptyCount;
            CurrentPlayer = other.CurrentPlayer;
            ActiveCount = other.ActiveCount;
            Threshold = other.Threshold;
            Phase = other.Phase;
            Winner = other.Winner;
        }

        public Coordinate CoordinateOf(int index) => new Coordinate(index % Width, index / Width);
        public int IndexOf(Coordinate cell)
        {
            if (!InBounds(cell.X, cell.Y)) throw new ArgumentOutOfRangeException(nameof(cell));
            return cell.Y * Width + cell.X;
        }
        public int OwnerAt(int index) => owners[index];
        public byte ConsumedDirectionsAt(int index) => consumed[index];
        public bool IsActive(int player) => player >= 0 && player < PlayerCount && active[player];
        public bool IsLegal(int index) => !IsTerminal && index >= 0 && index < CellCount && owners[index] < 0;
        private bool InBounds(int x, int y) => x >= 0 && x < Width && y >= 0 && y < Height;

        public int CountConnections(int move, int player)
        {
            if (move < 0 || move >= CellCount || owners[move] >= 0) return 0;
            if (player < 0 || player >= PlayerCount) throw new ArgumentOutOfRangeException(nameof(player));
            int mask = ConnectionMask(move, player), count = 0;
            for (int d = 0; d < 4; d++) count += (mask >> d) & 1;
            return count;
        }

        private int ConnectionMask(int move, int player)
        {
            int x = move % Width, y = move / Width, mask = 0;
            for (int d = 0; d < 4; d++)
            {
                int count = 1;
                bool alreadyScored = (consumed[move] & (1 << d)) != 0;
                for (int sign = -1; sign <= 1; sign += 2)
                    for (int xx = x + sign * Dx[d], yy = y + sign * Dy[d];
                         InBounds(xx, yy) && owners[yy * Width + xx] == player;
                         xx += sign * Dx[d], yy += sign * Dy[d])
                    {
                        count++;
                        alreadyScored |= (consumed[yy * Width + xx] & (1 << d)) != 0;
                    }
                if (count >= ConnectionLength && !alreadyScored) mask |= 1 << d;
            }
            return mask;
        }

        /// <summary>Applies a legal move with the same winner-before-draw ordering as GameState.</summary>
        public int Apply(int move)
        {
            if (!IsLegal(move) || !IsActive(CurrentPlayer))
                throw new InvalidOperationException("Cannot apply an illegal move.");
            int player = CurrentPlayer, mask = ConnectionMask(move, player), count = 0;
            owners[move] = player;
            EmptyCount--;
            int x = move % Width, y = move / Width;
            for (int d = 0; d < 4; d++)
            {
                if ((mask & (1 << d)) == 0) continue;
                count++;
                consumed[move] |= (byte)(1 << d);
                for (int sign = -1; sign <= 1; sign += 2)
                    for (int xx = x + sign * Dx[d], yy = y + sign * Dy[d];
                         InBounds(xx, yy) && owners[yy * Width + xx] == player;
                         xx += sign * Dx[d], yy += sign * Dy[d])
                        consumed[yy * Width + xx] |= (byte)(1 << d);
            }
            if (Phase == GameState.GameStateEnum.Cascade && count < Threshold)
            {
                active[player] = false;
                ActiveCount--;
                if (ActiveCount == 1)
                {
                    for (int p = 0; p < PlayerCount; p++)
                        if (active[p]) { CurrentPlayer = p; Winner = p; break; }
                    Phase = GameState.GameStateEnum.End;
                    return count;
                }
            }
            else if (count > 0)
            {
                Phase = GameState.GameStateEnum.Cascade;
                Threshold = count;
            }
            if (EmptyCount == 0)
            {
                Phase = GameState.GameStateEnum.End;
                Winner = null;
                return count;
            }
            for (int step = 1; step < PlayerCount; step++)
            {
                int next = (player + step) % PlayerCount;
                if (active[next]) { CurrentPlayer = next; break; }
            }
            return count;
        }

        /// <summary>Unconsumed, unblocked local windows; heuristic only, not a scoring oracle.</summary>
        public double Investment(int move, int player)
        {
            int x = move % Width, y = move / Width;
            double score = 0;
            for (int d = 0; d < 4; d++)
                for (int offset = 0; offset < ConnectionLength; offset++)
                {
                    int sx = x - offset * Dx[d], sy = y - offset * Dy[d];
                    if (!InBounds(sx, sy) ||
                        !InBounds(sx + (ConnectionLength - 1) * Dx[d], sy + (ConnectionLength - 1) * Dy[d]))
                        continue;
                    int own = 0;
                    bool blocked = false;
                    for (int k = 0; k < ConnectionLength; k++)
                    {
                        int cell = (sy + k * Dy[d]) * Width + sx + k * Dx[d];
                        if ((owners[cell] >= 0 && owners[cell] != player) ||
                            (consumed[cell] & (1 << d)) != 0) { blocked = true; break; }
                        if (owners[cell] == player) own++;
                    }
                    if (!blocked) score += own == 0 ? 0.05 : own * own;
                }
            return score;
        }

        public int FillEmptyMoves(int[] buffer)
        {
            if (buffer.Length < EmptyCount) throw new ArgumentException("Buffer too small.");
            int count = 0;
            for (int i = 0; i < CellCount; i++) if (owners[i] < 0) buffer[count++] = i;
            return count;
        }

        /// <summary>Stable input fingerprint, including history and turn context; not a security hash.</summary>
        public ulong Fingerprint()
        {
            ulong hash = 14695981039346656037UL;
            Mix(ref hash, Width); Mix(ref hash, Height); Mix(ref hash, PlayerCount);
            Mix(ref hash, ConnectionLength); Mix(ref hash, CurrentPlayer); Mix(ref hash, Threshold);
            Mix(ref hash, (int)Phase); Mix(ref hash, Winner ?? -1);
            for (int i = 0; i < CellCount; i++) { Mix(ref hash, owners[i]); Mix(ref hash, consumed[i]); }
            for (int p = 0; p < PlayerCount; p++) Mix(ref hash, active[p] ? 1 : 0);
            return hash;
        }

        private static void Mix(ref ulong hash, int value)
        {
            unchecked { hash = (hash ^ (uint)value) * 1099511628211UL; }
        }
    }
}
