// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
namespace TicTacCOSTCO.AIs.Search
{
    using System;

    public enum CpuStrength { Easy, Normal, Hard }
    public enum SearchStopReason { Running, WorkLimit, SimulationLimit, Deadline, Cancelled, NoLegalMove, Solved }

    [Serializable]
    public sealed class SearchSettings
    {
        // Logical work, not milliseconds: same seed/input/settings are reproducible
        // across frame slicing. Preset strength still requires empirical calibration.
        public int MaxWorkUnits = 32000;
        public int MaxSimulations = 512;
        public int MaxNodes = 1024;
        public int RolloutPlies = 24;
        public int RolloutCandidates = 8;
        public int InitialCandidates = 6;
        public int ExactEmptyLimit = 8;
        public double Exploration = 0.8;
        public double Widening = 1.5;
        public double RootChoiceNoise = 0;
        public double ActivationPreference = 0;
        public double InvestmentWeight = 1;
        public int Seed = 12345;

        public static SearchSettings ForStrength(CpuStrength strength)
        {
            switch (strength)
            {
                case CpuStrength.Easy:
                    return new SearchSettings { MaxWorkUnits = 6000, MaxSimulations = 64,
                        RolloutPlies = 8, InitialCandidates = 4, RootChoiceNoise = 0.15 };
                case CpuStrength.Hard:
                    return new SearchSettings { MaxWorkUnits = 128000, MaxSimulations = 2048,
                        RolloutPlies = 48, InitialCandidates = 8 };
                default: return new SearchSettings();
            }
        }

        public static SearchSettings ForPosition(CpuStrength strength, int emptyCells, int activePlayers)
        {
            var result = ForStrength(strength);
            // Shared smooth size/player adjustment, not a table of bespoke board bots.
            double complexity = Math.Min(8, Math.Max(1, Math.Sqrt(Math.Max(1, emptyCells) / 25.0) *
                Math.Sqrt(Math.Max(2, activePlayers) / 2.0)));
            result.MaxWorkUnits = (int)(result.MaxWorkUnits * complexity);
            return result;
        }

        internal SearchSettings ValidatedCopy()
        {
            var copy = (SearchSettings)MemberwiseClone();
            if (MaxWorkUnits < 0 || MaxSimulations < 0 || MaxNodes < 1 ||
                RolloutPlies < 1 || RolloutCandidates < 1 || InitialCandidates < 1 ||
                ExactEmptyLimit < 0 || ExactEmptyLimit > 10 ||
                !Finite(Exploration) || Exploration < 0 || !Finite(Widening) || Widening <= 0 ||
                !Finite(RootChoiceNoise) || RootChoiceNoise < 0 || RootChoiceNoise > 1 ||
                !Finite(ActivationPreference) || !Finite(InvestmentWeight) || InvestmentWeight < 0)
                throw new ArgumentOutOfRangeException(nameof(SearchSettings), "Invalid CPU search settings.");
            return copy;
        }

        private static bool Finite(double value) => !double.IsNaN(value) && !double.IsInfinity(value);
    }
}
