// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
namespace TicTacCOSTCO.Tests
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading;
    using NUnit.Framework;
    using TicTacCOSTCO.AIs.Search;
    using TicTacCOSTCO.DataStructures;
    using TicTacCOSTCO.DataStructures.Tools;

    public class CascadeSearchTests
    {
        private static GameState NewGame(int size = 5, int players = 2)
            => new GameState(size, size, players) { CurrentPlayerIndex = 0 };

        private static void Place(GameState game, int x, int y)
            => game.SetSideOwnership(new Coordinate(x, y), game.CurrentPlayerIndex, out _);

        private static GameState SurvivalPosition(int players = 2)
        {
            var game = NewGame(5, players);
            game.SpotToSideOwnership[new Coordinate(0, 0)] = 0;
            game.SpotToSideOwnership[new Coordinate(1, 0)] = 0;
            Place(game, 2, 0);
            game.SpotToSideOwnership[new Coordinate(0, 2)] = 1;
            game.SpotToSideOwnership[new Coordinate(1, 2)] = 1;
            return game;
        }

        private static CascadeSearch Finish(CascadePosition position, SearchSettings settings, int slice = 113)
        {
            var search = new CascadeSearch(position, settings);
            while (!search.IsComplete) search.Step(slice);
            return search;
        }

        [TestCase(3, 2)]
        [TestCase(5, 3)]
        [TestCase(8, 6)]
        [TestCase(12, 2)]
        [TestCase(20, 6)]
        public void SnapshotAndTransitionsMatchAuthoritativeGame(int size, int players)
        {
            // All players' hypothetical scores and every transition are checked,
            // including history masks. This is a differential test, not a copy of
            // the new scorer used as its own oracle.
            for (int seed = 0; seed < 12; seed++)
            {
                var random = new Random(seed + size * 100);
                var game = NewGame(size, players);
                var position = CascadePosition.Capture(game);
                for (int turn = 0; turn < size * size && !position.IsTerminal; turn++)
                {
                    var moves = game.GetEmptySpots();
                    foreach (var move in moves)
                        for (int p = 0; p < players; p++)
                            Assert.AreEqual(HypotheticalSolutionTool.GetSolutionsFromClaimingTile(game, move, p).Count,
                                position.CountConnections(position.IndexOf(move), p),
                                $"score seed={seed}, turn={turn}, player={p}, move={move}");
                    var chosen = moves[random.Next(moves.Count)];
                    // Half of games deliberately seek scoring/survival to exercise
                    // consumed directions and elimination rather than only quiet draws.
                    if ((seed & 1) == 0)
                    {
                        int best = -1;
                        foreach (var move in moves)
                        {
                            int score = HypotheticalSolutionTool.GetSolutionsFromClaimingTile(game, move, game.CurrentPlayerIndex).Count;
                            if (score > best) { best = score; chosen = move; }
                        }
                    }
                    int count = position.Apply(position.IndexOf(chosen));
                    game.SetSideOwnership(chosen, game.CurrentPlayerIndex, out var solutions);
                    Assert.AreEqual(solutions.Count, count);
                    Assert.AreEqual(CascadePosition.Capture(game).Fingerprint(), position.Fingerprint(),
                        $"transition seed={seed}, turn={turn}");
                }
                Assert.IsTrue(position.IsTerminal);
            }
        }

        [Test]
        public void FourAxesScoreFourNotNumberOfThreeCellWindows()
        {
            var game = NewGame();
            foreach (var c in new[] { new Coordinate(0, 2), new Coordinate(1, 2),
                new Coordinate(2, 0), new Coordinate(2, 1), new Coordinate(0, 0),
                new Coordinate(1, 1), new Coordinate(3, 1), new Coordinate(4, 0) })
                game.SpotToSideOwnership[c] = 0;
            var position = CascadePosition.Capture(game);
            Assert.AreEqual(4, position.CountConnections(position.IndexOf(new Coordinate(2, 2)), 0));
            Assert.AreEqual(4, position.Apply(position.IndexOf(new Coordinate(2, 2))));
            Assert.AreEqual(4, position.Threshold);
        }

        [Test]
        public void RectangularBoardsAndDifferentConnectionLengthsRemainRuleEquivalent()
        {
            var game = new GameState(7, 3, 2) { CurrentPlayerIndex = 0, InARowToSolve = 4 };
            for (int x = 0; x < 3; x++) game.SpotToSideOwnership[new Coordinate(x, 1)] = 0;
            var position = CascadePosition.Capture(game);
            Assert.AreEqual(1, position.CountConnections(position.IndexOf(new Coordinate(3, 1)), 0));
            position.Apply(position.IndexOf(new Coordinate(3, 1)));
            Place(game, 3, 1);
            Assert.AreEqual(CascadePosition.Capture(game).Fingerprint(), position.Fingerprint());
            Assert.AreEqual(0, position.CountConnections(position.IndexOf(new Coordinate(4, 1)), 0));
        }

        [Test]
        public void ExtendingConsumedLineScoresZeroAndHistoryChangesFingerprint()
        {
            var game = NewGame();
            game.SpotToSideOwnership[new Coordinate(0, 0)] = 0;
            game.SpotToSideOwnership[new Coordinate(1, 0)] = 0;
            Place(game, 2, 0);
            var position = CascadePosition.Capture(game);
            Assert.AreEqual(0, position.CountConnections(position.IndexOf(new Coordinate(3, 0)), 0));
            ulong original = position.Fingerprint();
            game.AcceptedSolutions.Clear();
            var unconsumed = CascadePosition.Capture(game);
            Assert.AreEqual(1, unconsumed.CountConnections(unconsumed.IndexOf(new Coordinate(3, 0)), 0));
            Assert.AreNotEqual(original, unconsumed.Fingerprint());
        }

        [Test]
        public void FullBoardIsDrawEvenIfLastMoveMakesFirstConnection()
        {
            var game = NewGame(3);
            for (int y = 0; y < 3; y++)
                for (int x = 0; x < 3; x++)
                    if (x != 2 || y != 2) game.SpotToSideOwnership[new Coordinate(x, y)] = 0;
            var position = CascadePosition.Capture(game);
            position.Apply(8);
            Place(game, 2, 2);
            Assert.IsTrue(position.IsTerminal);
            Assert.IsNull(position.Winner);
            Assert.AreEqual(CascadePosition.Capture(game).Fingerprint(), position.Fingerprint());
        }

        [Test]
        public void LastSurvivorWinsBeforeFullBoardDraw()
        {
            var game = NewGame(3);
            game.SpotToSideOwnership[new Coordinate(0, 0)] = 0;
            game.SpotToSideOwnership[new Coordinate(1, 0)] = 0;
            Place(game, 2, 0);
            for (int y = 1; y < 3; y++)
                for (int x = 0; x < 3; x++)
                    if (x != 2 || y != 2) game.SpotToSideOwnership[new Coordinate(x, y)] = 0;
            var position = CascadePosition.Capture(game);
            position.Apply(8);
            Place(game, 2, 2);
            Assert.AreEqual(0, position.EmptyCount);
            Assert.AreEqual(0, position.Winner);
            Assert.AreEqual(CascadePosition.Capture(game).Fingerprint(), position.Fingerprint());
        }

        [Test]
        public void EliminationPreservesMarksThresholdAndSkipsEliminatedPlayers()
        {
            var game = SurvivalPosition(3);
            var position = CascadePosition.Capture(game);
            position.Apply(position.IndexOf(new Coordinate(4, 4)));
            Assert.IsFalse(position.IsActive(1));
            Assert.AreEqual(1, position.OwnerAt(position.IndexOf(new Coordinate(4, 4))));
            Assert.AreEqual(1, position.Threshold);
            Assert.AreEqual(2, position.CurrentPlayer);
            Assert.AreEqual(2, position.ActiveCount);
        }

        [TestCase(2)]
        [TestCase(3)]
        [TestCase(6)]
        public void CompletedRootScanAlwaysFindsOnlySurvivalMove(int players)
        {
            var position = CascadePosition.Capture(SurvivalPosition(players));
            var settings = new SearchSettings { MaxWorkUnits = position.EmptyCount + 1 };
            using (var search = Finish(position, settings))
            {
                Assert.IsTrue(search.RootScanComplete);
                Assert.AreEqual(new Coordinate(2, 2), search.BestMove);
            }
        }

        [TestCase(CpuStrength.Easy)]
        [TestCase(CpuStrength.Normal)]
        [TestCase(CpuStrength.Hard)]
        public void AllPresetsPreserveForcedSurvival(CpuStrength strength)
        {
            var position = CascadePosition.Capture(SurvivalPosition());
            using (var search = Finish(position, SearchSettings.ForStrength(strength)))
                Assert.AreEqual(new Coordinate(2, 2), search.BestMove);
        }

        [TestCase(3, 2)]
        [TestCase(5, 3)]
        [TestCase(8, 6)]
        [TestCase(12, 2)]
        [TestCase(20, 6)]
        public void SearchIsLegalBoundedAndDoesNotMutateInput(int size, int players)
        {
            var position = CascadePosition.Capture(NewGame(size, players));
            ulong before = position.Fingerprint();
            using (var search = Finish(position, new SearchSettings { MaxWorkUnits = 3500, MaxNodes = 4 }))
            {
                Assert.IsTrue(search.BestMove.HasValue);
                Assert.IsTrue(position.IsLegal(position.IndexOf(search.BestMove.Value)));
                Assert.LessOrEqual(search.WorkUnits, 3500);
                Assert.LessOrEqual(search.NodeCount, 4);
                Assert.AreEqual(before, position.Fingerprint());
            }
        }

        [Test]
        public void SeedAndWorkAreIndependentOfFrameSlicing()
        {
            var position = CascadePosition.Capture(NewGame());
            var settings = new SearchSettings { MaxWorkUnits = 18000, Seed = 90210, RootChoiceNoise = .5 };
            using (var a = Finish(position, settings, 1))
            using (var b = Finish(position, settings, 257))
            {
                Assert.AreEqual(a.BestMove, b.BestMove);
                Assert.AreEqual(a.Simulations, b.Simulations);
                Assert.AreEqual(a.NodeCount, b.NodeCount);
                Assert.AreEqual(a.WorkUnits, b.WorkUnits);
                Assert.AreEqual(a.StopReason, b.StopReason);
            }
        }

        [Test]
        public void ZeroBudgetCancellationAndDeadlineKeepLegalFallback()
        {
            var position = CascadePosition.Capture(NewGame());
            using (var zero = Finish(position, new SearchSettings { MaxWorkUnits = 0 }))
            {
                Assert.AreEqual(0, zero.WorkUnits);
                Assert.IsTrue(position.IsLegal(position.IndexOf(zero.BestMove.Value)));
                Assert.AreEqual(SearchStopReason.WorkLimit, zero.StopReason);
            }
            using (var cancelled = new CascadeSearch(position, new SearchSettings()))
            {
                cancelled.Step(20, new CancellationToken(true));
                Assert.AreEqual(0, cancelled.WorkUnits);
                Assert.AreEqual(SearchStopReason.Cancelled, cancelled.StopReason);
                Assert.IsTrue(cancelled.BestMove.HasValue);
                cancelled.Step(100);
                Assert.AreEqual(0, cancelled.WorkUnits);
            }
            using (var deadline = new CascadeSearch(position, new SearchSettings()))
            {
                deadline.Step(10);
                deadline.Stop(SearchStopReason.Deadline);
                Assert.AreEqual(SearchStopReason.Deadline, deadline.StopReason);
                Assert.IsTrue(deadline.BestMove.HasValue);
            }
        }

        [Test]
        public void TerminalPositionReturnsNoMove()
        {
            var game = NewGame(3);
            for (int y = 0; y < 3; y++)
                for (int x = 0; x < 3; x++)
                    game.SpotToSideOwnership[new Coordinate(x, y)] = 0;
            // Mutator is used here only to signal the existing terminal rule.
            Place(game, 2, 2);
            using (var search = Finish(CascadePosition.Capture(game), new SearchSettings()))
            {
                Assert.AreEqual(SearchStopReason.NoLegalMove, search.StopReason);
                Assert.IsNull(search.BestMove);
            }
        }

        [Test]
        public void IllegalMovesAndInvalidSettingsFailExplicitly()
        {
            var position = CascadePosition.Capture(NewGame());
            position.Apply(0);
            Assert.Throws<InvalidOperationException>(() => position.Apply(0));
            Assert.Throws<InvalidOperationException>(() => position.Apply(-1));
            Assert.Throws<ArgumentOutOfRangeException>(() => new CascadeSearch(position, new SearchSettings { MaxNodes = 0 }));
            Assert.Throws<ArgumentOutOfRangeException>(() => new CascadeSearch(position, new SearchSettings { Exploration = double.NaN }));
        }

        [Test]
        public void SnapshotOwnsItsArraysAndSearchCopiesSettings()
        {
            var game = NewGame();
            var position = CascadePosition.Capture(game);
            ulong before = position.Fingerprint();
            var settings = new SearchSettings { MaxWorkUnits = 100 };
            using (var search = new CascadeSearch(position, settings))
            {
                Place(game, 0, 0);
                Assert.AreEqual(before, position.Fingerprint());
                settings.MaxWorkUnits = 0;
                search.Step(200);
                Assert.AreEqual(100, search.WorkUnits);
            }
        }

        [Test]
        public void RotationsPreserveScoresIncludingConsumedHistory()
        {
            var game = SurvivalPosition(3);
            var rotated = NewGame(5, 3);
            // Rotate the construction, including the scoring event.
            rotated.SpotToSideOwnership[new Coordinate(4, 0)] = 0;
            rotated.SpotToSideOwnership[new Coordinate(4, 1)] = 0;
            Place(rotated, 4, 2);
            rotated.SpotToSideOwnership[new Coordinate(2, 0)] = 1;
            rotated.SpotToSideOwnership[new Coordinate(2, 1)] = 1;
            var a = CascadePosition.Capture(game);
            var b = CascadePosition.Capture(rotated);
            for (int y = 0; y < 5; y++)
                for (int x = 0; x < 5; x++)
                    for (int p = 0; p < 3; p++)
                        Assert.AreEqual(a.CountConnections(a.IndexOf(new Coordinate(x, y)), p),
                            b.CountConnections(b.IndexOf(new Coordinate(4 - y, x)), p));
        }

        [Test]
        public void TinyTwoPlayerPositionsMatchExhaustiveIndependentMinimax()
        {
            int checkedPositions = 0;
            for (int seed = 0; seed < 40; seed++)
            {
                var game = NewGame(3);
                var random = new Random(seed);
                var history = new List<Coordinate>();
                for (int turn = 0; turn < 4 && game.CurrentGameState != GameState.GameStateEnum.End; turn++)
                {
                    var moves = game.GetEmptySpots();
                    var move = moves[random.Next(moves.Count)];
                    history.Add(move);
                    game.SetSideOwnership(move, game.CurrentPlayerIndex, out _);
                }
                if (game.CurrentGameState == GameState.GameStateEnum.End) continue;
                int rootPlayer = game.CurrentPlayerIndex;
                double optimal = ReferenceMinimax(history, rootPlayer);
                using (var search = Finish(CascadePosition.Capture(game),
                    new SearchSettings { MaxWorkUnits = 100000, RootChoiceNoise = 1 }))
                {
                    Assert.IsTrue(search.IsProven);
                    Assert.AreEqual(SearchStopReason.Solved, search.StopReason);
                    history.Add(search.BestMove.Value);
                    Assert.AreEqual(optimal, ReferenceMinimax(history, rootPlayer), $"seed={seed}");
                }
                checkedPositions++;
            }
            Assert.GreaterOrEqual(checkedPositions, 20);
        }

        private static double ReferenceMinimax(List<Coordinate> history, int rootPlayer)
        {
            // Independent, deliberately slow oracle: rebuild and replay the actual
            // GameState on every branch. Does not use CascadePosition or pruning.
            var game = NewGame(3);
            foreach (var move in history) game.SetSideOwnership(move, game.CurrentPlayerIndex, out _);
            if (game.CurrentGameState == GameState.GameStateEnum.End)
                return game.Winner.HasValue ? (game.Winner.Value == rootPlayer ? 1 : 0) : .5;
            bool maximizing = game.CurrentPlayerIndex == rootPlayer;
            double value = maximizing ? double.NegativeInfinity : double.PositiveInfinity;
            foreach (var move in game.GetEmptySpots())
            {
                history.Add(move);
                double child = ReferenceMinimax(history, rootPlayer);
                history.RemoveAt(history.Count - 1);
                value = maximizing ? Math.Max(value, child) : Math.Min(value, child);
            }
            return value;
        }

        [Test]
        public void InterruptedExactSearchNeverClaimsProof()
        {
            var game = NewGame(3);
            Place(game, 1, 1);
            var position = CascadePosition.Capture(game);
            using (var search = Finish(position, new SearchSettings { MaxWorkUnits = 12 }))
            {
                Assert.IsTrue(search.RootScanComplete);
                Assert.IsFalse(search.IsProven);
                Assert.AreEqual(SearchStopReason.WorkLimit, search.StopReason);
                Assert.IsTrue(position.IsLegal(position.IndexOf(search.BestMove.Value)));
            }
        }

        [Test]
        public void SharedComplexityScalingKeepsStrengthBudgetsOrdered()
        {
            foreach (int cells in new[] { 9, 25, 64, 144, 400 })
                foreach (int players in new[] { 2, 3, 6 })
                {
                    int easy = SearchSettings.ForPosition(CpuStrength.Easy, cells, players).MaxWorkUnits;
                    int normal = SearchSettings.ForPosition(CpuStrength.Normal, cells, players).MaxWorkUnits;
                    int hard = SearchSettings.ForPosition(CpuStrength.Hard, cells, players).MaxWorkUnits;
                    Assert.Less(easy, normal);
                    Assert.Less(normal, hard);
                }
        }

        [Test, Explicit("Desktop smoke benchmark, not Android performance or calibrated strength evidence.")]
        public void BenchmarkPresetsAndBoardSizes()
        {
            foreach (int size in new[] { 3, 5, 8, 12, 20 })
                foreach (int players in new[] { 2, 3, 6 })
                    foreach (CpuStrength strength in Enum.GetValues(typeof(CpuStrength)))
                    {
                        var position = CascadePosition.Capture(NewGame(size, players));
                        using (var warmup = Finish(position, SearchSettings.ForPosition(strength, position.EmptyCount, players))) { }
                        var watch = Stopwatch.StartNew();
                        long allocated = GC.GetAllocatedBytesForCurrentThread();
                        using (var search = Finish(position, SearchSettings.ForPosition(strength, position.EmptyCount, players)))
                            TestContext.WriteLine($"{size}x{size},players={players},{strength},work={search.WorkUnits}," +
                                $"simulations={search.Simulations},nodes={search.NodeCount},ms={watch.Elapsed.TotalMilliseconds:F2}," +
                                $"allocated={GC.GetAllocatedBytesForCurrentThread() - allocated},move={search.BestMove}");
                    }
        }
    }
}
