// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
using System;
using NUnit.Framework;
using TicTacCOSTCO.AIs.Search;
using TicTacCOSTCO.DataStructures;

[TestFixture]
public class BaselineTests
{
    [Test]
    public void AdapterRejectsWrongSideAndCreatesLegalSearch()
    {
        var game = new GameState(5, 5, 2) { CurrentPlayerIndex = 0 };
        var core = new AISearchCore();
        Assert.Throws<ArgumentException>(() => core.BeginSearch(1, game));
        using (var search = core.BeginSearch(0, game))
        {
            while (!search.IsComplete) search.Step(100);
            Assert.IsTrue(search.BestMove.HasValue);
            Assert.IsNull(game.SpotToSideOwnership[search.BestMove.Value]);
        }
    }

    [Test, Explicit("Exploratory desktop league using legacy algorithm bodies and a seeded headless RNG shim.")]
    public void PairedLegacyLeague()
    {
        AICore[] opponents = { new AICore(), new AIDoNotLoseSimple(), new AIInvestor(),
            new AIMayAttack { OneConnectionChance = .05f, TwoConnectionChance = 1, ThreeOrMoreConnectionChance = 1 } };
        foreach (int size in new[] { 5, 8 })
            foreach (AICore opponent in opponents)
            {
                int wins = 0, losses = 0, draws = 0, moves = 0;
                for (int seed = 0; seed < 8; seed++)
                    for (int seat = 0; seat < 2; seat++)
                    {
                        var game = new GameState(size, size, 2) { CurrentPlayerIndex = 0 };
                        UnityEngine.Random.InitState(seed);
                        int turns = 0;
                        while (game.CurrentGameState != GameState.GameStateEnum.End)
                        {
                            int player = game.CurrentPlayerIndex;
                            Coordinate move;
                            if (player == seat)
                            {
                                var position = CascadePosition.Capture(game);
                                var settings = SearchSettings.ForPosition(CpuStrength.Normal, position.EmptyCount, position.ActiveCount);
                                settings.Seed = unchecked(seed ^ (int)position.Fingerprint());
                                using (var search = new CascadeSearch(position, settings))
                                {
                                    while (!search.IsComplete) search.Step(1000);
                                    Assert.IsTrue(search.BestMove.HasValue);
                                    move = search.BestMove.Value;
                                }
                            }
                            else move = opponent.DetermineMove(player, game);
                            Assert.IsNull(game.SpotToSideOwnership[move], "Every tournament move must be legal.");
                            game.SetSideOwnership(move, player, out _);
                            Assert.LessOrEqual(++turns, size * size);
                        }
                        moves += turns;
                        if (!game.Winner.HasValue) draws++;
                        else if (game.Winner.Value == seat) wins++;
                        else losses++;
                    }
                TestContext.WriteLine($"board={size},opponent={opponent.GetType().Name},wins={wins},losses={losses},draws={draws},moves={moves}");
            }
    }

    [Test, Explicit("Exploratory multi-player completion league, not a strength guarantee.")]
    public void MultiplayerLeague()
    {
        var opponent = new AIMayAttack { OneConnectionChance = .05f, TwoConnectionChance = 1, ThreeOrMoreConnectionChance = 1 };
        foreach (int players in new[] { 3, 6 })
            foreach (int size in new[] { 5, 8 })
            {
                int wins = 0, losses = 0, draws = 0;
                for (int run = 0; run < 12; run++)
                {
                    var game = new GameState(size, size, players) { CurrentPlayerIndex = run % players };
                    int seat = (run / players) % players;
                    UnityEngine.Random.InitState(run);
                    int turns = 0;
                    while (game.CurrentGameState != GameState.GameStateEnum.End)
                    {
                        Coordinate move;
                        if (game.CurrentPlayerIndex == seat)
                        {
                            var position = CascadePosition.Capture(game);
                            var settings = SearchSettings.ForPosition(CpuStrength.Normal, position.EmptyCount, position.ActiveCount);
                            settings.Seed = run;
                            using (var search = new CascadeSearch(position, settings))
                            {
                                while (!search.IsComplete) search.Step(1000);
                                move = search.BestMove.Value;
                            }
                        }
                        else move = opponent.DetermineMove(game.CurrentPlayerIndex, game);
                        Assert.IsNull(game.SpotToSideOwnership[move]);
                        game.SetSideOwnership(move, game.CurrentPlayerIndex, out _);
                        Assert.LessOrEqual(++turns, size * size);
                    }
                    if (!game.Winner.HasValue) draws++;
                    else if (game.Winner.Value == seat) wins++;
                    else losses++;
                }
                TestContext.WriteLine($"board={size},players={players},wins={wins},losses={losses},draws={draws}");
            }
    }

    [Test, Explicit("Exploratory difficulty ordering; not an assertion of monotonic strength.")]
    public void DifficultyLeague()
    {
        foreach (int size in new[] { 5, 8 })
            foreach (CpuStrength lower in new[] { CpuStrength.Easy, CpuStrength.Normal })
            {
                CpuStrength higher = (CpuStrength)((int)lower + 1);
                int wins = 0, losses = 0, draws = 0;
                for (int seed = 100; seed < 108; seed++)
                    for (int seat = 0; seat < 2; seat++)
                    {
                        var game = new GameState(size, size, 2) { CurrentPlayerIndex = 0 };
                        while (game.CurrentGameState != GameState.GameStateEnum.End)
                        {
                            var position = CascadePosition.Capture(game);
                            var strength = game.CurrentPlayerIndex == seat ? higher : lower;
                            var settings = SearchSettings.ForPosition(strength, position.EmptyCount, position.ActiveCount);
                            settings.Seed = unchecked(seed ^ (int)position.Fingerprint());
                            using (var search = new CascadeSearch(position, settings))
                            {
                                while (!search.IsComplete) search.Step(1000);
                                game.SetSideOwnership(search.BestMove.Value, game.CurrentPlayerIndex, out _);
                            }
                        }
                        if (!game.Winner.HasValue) draws++;
                        else if (game.Winner.Value == seat) wins++;
                        else losses++;
                    }
                TestContext.WriteLine($"board={size},{higher}-vs-{lower},wins={wins},losses={losses},draws={draws}");
            }
    }
}
