// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
using NUnitLite;

internal static class Program
{
    private static int Main(string[] args) => new AutoRun().Execute(args);
}
