// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using TicTacCOSTCO.DataStructures;
using TicTacCOSTCO.Unity.UI;

public class TurnLoopSmokeTests
{
    private static void Lifecycle(AIThinkerLoop loop, string name)
        => typeof(AIThinkerLoop).GetMethod(name, BindingFlags.NonPublic | BindingFlags.Instance).Invoke(loop, null);

    private static AIThinkerLoop NewLoop()
    {
        var game = new GameState(20, 20, 2) { CurrentPlayerIndex = 0 };
        var conductor = new GameConductor { CurrentGameState = game };
        var turns = new TurnOrderHolder();
        game.OnPlayerTurn += p => turns.OnTurnStarted?.Invoke(p);
        return new AIThinkerLoop { GameConductor = conductor, TurnOrderHolder = turns,
            BasicAICore = new AISearchCore { FrameBudgetMilliseconds = .1f, WorkBudgetScale = 4,
                MoveTimeLimitMilliseconds = 10000 } };
    }

    [Test]
    public void ResetCancelsInFlightSearchAndOldCoroutineCannotApply()
    {
        var loop = NewLoop();
        Lifecycle(loop, "OnEnable");
        var old = loop.Scheduled.Single();
        Assert.IsTrue(old.Advance());
        Assert.AreEqual(0, loop.GameConductor.MovesApplied);
        loop.GameConductor.Reset(new GameState(3, 3, 2) { CurrentPlayerIndex = 0 });
        Assert.IsFalse(old.Advance());
        Assert.AreEqual(0, loop.GameConductor.MovesApplied);
        Lifecycle(loop, "OnDisable");
    }

    [TestCase("version")]
    [TestCase("human")]
    [TestCase("identity")]
    public void ChangedTurnContextDiscardsResult(string change)
    {
        var loop = NewLoop();
        Lifecycle(loop, "OnEnable");
        var old = loop.Scheduled.Single();
        Assert.IsTrue(old.Advance());
        if (change == "version") loop.GameConductor.StateVersion++;
        if (change == "human") loop.TurnOrderHolder.Humans.Add(0);
        if (change == "identity") loop.GameConductor.CurrentGameState = new GameState(20, 20, 2);
        Assert.IsFalse(old.Advance());
        Assert.AreEqual(0, loop.GameConductor.MovesApplied);
        Lifecycle(loop, "OnDisable");
    }

    [Test]
    public void DisableCancelsPendingWorkAndUnsubscribes()
    {
        var loop = NewLoop();
        Lifecycle(loop, "OnEnable");
        var old = loop.Scheduled.Single();
        Lifecycle(loop, "OnDisable");
        Assert.IsFalse(old.Advance());
        loop.TurnOrderHolder.OnTurnStarted?.Invoke(0);
        Assert.AreEqual(1, loop.Scheduled.Count);
        Assert.AreEqual(0, loop.GameConductor.MovesApplied);
    }

    [Test]
    public void BackToBackComputerTurnsHaveOnlyOnePendingCoroutine()
    {
        var loop = NewLoop();
        loop.GameConductor.CurrentGameState = new GameState(3, 3, 2) { CurrentPlayerIndex = 0 };
        loop.GameConductor.CurrentGameState.OnPlayerTurn += p => loop.TurnOrderHolder.OnTurnStarted?.Invoke(p);
        Lifecycle(loop, "OnEnable");
        int iterations = 0;
        while (loop.GameConductor.CurrentGameState.CurrentGameState != GameState.GameStateEnum.End)
        {
            var pending = loop.Scheduled.Where(c => !c.Stopped).ToArray();
            Assert.AreEqual(1, pending.Length);
            pending[0].Advance();
            Assert.Less(++iterations, 10000);
        }
        Assert.Greater(loop.GameConductor.MovesApplied, 0);
        Assert.LessOrEqual(loop.GameConductor.MovesApplied, 9);
        Lifecycle(loop, "OnDisable");
    }

    [Test]
    public void LegacySynchronousCoreRemainsSupported()
    {
        var loop = NewLoop();
        loop.BasicAICore = new AICore();
        Lifecycle(loop, "OnEnable");
        var coroutine = loop.Scheduled.Single();
        coroutine.Advance();
        Assert.AreEqual(1, loop.GameConductor.MovesApplied);
        Lifecycle(loop, "OnDisable");
    }
}
