// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
// HEADLESS ONLY. These minimal API shapes allow the unchanged legacy AI algorithm
// bodies and ScriptableObject adapter to compile in the console tests.
// They do NOT emulate Unity's engine, coroutine scheduling, serialization, or RNG.
// This file is outside Assets and is never part of a Unity build.
namespace UnityEngine
{
    using System;
    public class ScriptableObject { }
    [AttributeUsage(AttributeTargets.Class)]
    public sealed class CreateAssetMenuAttribute : Attribute
    {
        public string fileName;
        public string menuName;
    }
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class RangeAttribute : Attribute { public RangeAttribute(float min, float max) { } }
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class MinAttribute : Attribute { public MinAttribute(float min) { } }
    public static class Mathf
    {
        public static float Clamp(float value, float min, float max) => Math.Max(min, Math.Min(max, value));
        public static float Max(float a, float b) => Math.Max(a, b);
    }
    public static class Debug { public static void Log(object message) { } }
    public static class Random
    {
        private static System.Random rng = new System.Random(1);
        public static void InitState(int seed) { rng = new System.Random(seed); }
        public static float value => (float)rng.NextDouble();
        public static int Range(int min, int max) => rng.Next(min, max);
        public static float Range(float min, float max) => min + (max - min) * (float)rng.NextDouble();
    }
}
namespace UnityEngine.UIElements { }
namespace UnityEngine.Assertions.Must { }
