// Chiefly generated by Perplexity Computer (AI assistant). See Docs/AI-PROVENANCE.md.
// Headless control-flow smoke fixtures, not an engine/lifecycle emulator.
using System;
using System.Collections;
using System.Collections.Generic;
using TicTacCOSTCO.DataStructures;

namespace UnityEngine
{
    public sealed class Coroutine
    {
        public IEnumerator Routine;
        public bool Stopped;
        public bool Advance()
        {
            if (Stopped) return false;
            if (Routine.MoveNext()) return true;
            Stopped = true;
            return false;
        }
    }
    public class MonoBehaviour
    {
        public readonly List<Coroutine> Scheduled = new List<Coroutine>();
        public Coroutine StartCoroutine(IEnumerator routine)
        {
            var coroutine = new Coroutine { Routine = routine };
            Scheduled.Add(coroutine);
            coroutine.Advance();
            return coroutine;
        }
        public void StopCoroutine(Coroutine coroutine)
        {
            coroutine.Stopped = true;
            (coroutine.Routine as IDisposable)?.Dispose();
        }
    }
    public sealed class WaitForSeconds { public WaitForSeconds(float seconds) { } }
    public sealed class AnimationCurve { public float Evaluate(float value) => 0; }
}

namespace TicTacCOSTCO.Unity.UI
{
    public sealed class TurnOrderHolder
    {
        public Action<int> OnTurnStarted;
        public readonly HashSet<int> Humans = new HashSet<int>();
        public bool PlayerIsHuman(int player) => Humans.Contains(player);
    }
    public sealed class GameConductor
    {
        public GameState CurrentGameState;
        public long StateVersion;
        public event Action OnGameReset;
        public int MovesApplied;
        public void ChooseCell(Coordinate move)
        {
            StateVersion++;
            if (CurrentGameState.SpotToSideOwnership[move].HasValue) throw new Exception("Occupied move.");
            MovesApplied++;
            CurrentGameState.SetSideOwnership(move, CurrentGameState.CurrentPlayerIndex, out _);
        }
        public void Reset(GameState next)
        {
            StateVersion++;
            OnGameReset?.Invoke();
            CurrentGameState = next;
        }
    }
}
